### PR TITLE
pull request 2013-10-02 from Mohan

### PR DESCRIPTION
**Pull request by mohan43u**
Hi Shrini,

I have some changes, Please review and take it.

1) fixed noise issue when debugging is enabled
2) By Default, Disabled Alsa, Soundtouch, oggvorbis and only enabled Gstreamer

Please test whether pulseaudio works or not in your machine.

### CODE REVIEW

**Comment by mohan43u** [comment]
1) libtool by default compiles with -fPIC, so there is no need to manually put -fpic.
2) I'm using emacs, src/gstplay.c is indented when I look it in emacs. Not sure about how it looks in vi though.

**Comment by prasannatsm** [comment]
1. No problem then :)
2. Certain part of the src/gstplay.c has 2 spaces instead of a tab and in some places there is a tab. It will be better if we could follow a consistent coding style for dhvani.

**Comment by mohan43u** [comment]
I googled for C mode in both emacs & vi, It seems either we have to set modeline for vi as first line or modeline for emacs as first line. So, there is no way to set modeline for both emacs and vi.

I can remove the tabs and insert spaces without changing the indentation in gstplay.c. But making sure gstplay.c look pretty in vi is not in my hand. Either vi need to understand emacs's indentation rules, or emacs need to understand vi rules. If you can find a solution to this problem, let me know. I'll do whatever needs to be done in emacs side.

Anyway, just want to say, please avoid another holy war, because xkcd already said emacs have butterfly http://xkcd.com/378/

**Comment by prasannatsm** [comment]
Indentation does not have anything to do with vi or emacs. The code should look consistent even if opened in a dumb text editor. Don't use space use tabs - in other files tabs are used for indentation.

**Comment by mohan43u** [comment]
I don't know howto disable default indentation for C in emacs. In my opinion, we have to care about the code quality, not about code appearence. The existing code already sucks, we have to focus on fixing the issues instead of fighting for appearence.

Let the code as it is and we can write a script (or find a method) to make it look good afterwards. Putting rule on code indentation is bad for a project. None of the popular projects insist on indentation, they only insist on coding style.

**Comment by prasannatsm** [comment]
Indentation is part of coding style so I am trying to emphasis that. Rationale behind coding style / indentation is explained neatly in https://www.kernel.org/doc/Documentation/CodingStyle. We can follow any coding style but it should be consistent in a project.

Let the code be merged. I can indent the code.

**Comment by mohan43u** [comment]
Hi Shrini/Prasanna,

Could you please merge this request?

**Comment by prasannatsm** [comment]
Github says it is not able to merge pull request automatically - May due to changes made by me. I think Srini is the better person to merge this changes than me.

**Comment by tshrinivasan** [comment]
Will do tonight

**Comment by prasannatsm** [comment]
Shrini please merge the changes. I am planning to do some changes.

**Comment by tshrinivasan** [comment]
Ran the following commands.

git clone https://github.com/mohan43u/dhvani-tts.git

Step 1: Check out a new branch to test the changes — run this from your project directory

git checkout -b mohan43u-master master

Step 2: Bring in mohan43u's changes and test

git pull https://github.com/mohan43u/dhvani-tts.git master

Step 3: Merge the changes and update the server

git checkout master
git merge mohan43u-master
git push origin master

---

shrinivasan@shrinivasan:~/dhvani/mohan/dhvani-tts> git checkout master
Switched to branch 'master'
shrinivasan@shrinivasan:~/dhvani/mohan/dhvani-tts> git merge mohan43u-master
Already up-to-date.
shrinivasan@shrinivasan:~/dhvani/mohan/dhvani-tts> git push origin master
remote: Permission to mohan43u/dhvani-tts.git denied to tshrinivasan.
fatal: unable to access 'https://github.com/mohan43u/dhvani-tts.git/': The requested URL returned error: 403
shrinivasan@shrinivasan:~/dhvani/mohan/dhvani-tts> git push origin master
remote: Permission to mohan43u/dhvani-tts.git denied to tshrinivasan.
fatal: unable to access 'https://github.com/mohan43u/dhvani-tts.git/': The requested URL returned error: 403

Mohan,

give permission for me to access your repo.

my id is tshrinivasan

**Comment by prasannatsm** [comment]
Shrini you are trying to update mohan's repo and not yours. You can merge changes to your repo. Mohan and I will pull your changes.

**Comment by prasannatsm** [comment]
There is conflicts in merging the code.
1. Please pull the latest code from shrini's repo
2. Rebase your changes on top of shrini repo's master
3. After doing that test your changes and create another pull request which can be merged easily.

**Comment by prasannatsm** [comment]
Issue 1:
After resolving the conflict, While running make I am getting the following error (gstreamer headers are not installed in this case):

/bin/bash ../libtool --tag=CC   --mode=link gcc   -DDATABASEPATH=/usr/local/share/dhvani/database     -o dhvani dhvani-dhvani.o -ldhvani -lgsm 
libtool: link: gcc -DDATABASEPATH=/usr/local/share/dhvani/database -o .libs/dhvani dhvani-dhvani.o  /home/prasanna/Software/dhvani-tts/src/.libs/libdhvani.so -lgsm
/home/prasanna/Software/dhvani-tts/src/.libs/libdhvani.so: undefined reference to `alsa_play'
/home/prasanna/Software/dhvani-tts/src/.libs/libdhvani.so: undefined reference to`floor'

The linking is not handled correctly in the Makefile (or in the configure script). The patch breaks the older functionality.

Issue 2:
I installed gstaremer devel package but configure script is not detecting gstreamer headers. Am I missing something here?

**Comment by mohan43u** [comment]
Hi Prasanna,

Issue1: use --with-alsa to enable alsa support
Issue2: what is the output of 'pkg-config --cflags --libs gstreamer-1.0 gstreamer-plugins-bad-1.0 gstreamer-plugins-base-1.0'?

**Comment by mohan43u** [comment]
Hi Prasanna,

I updated my master from srini's master. You can merge this request, I hope it will not show any conflict.

**Comment by prasannatsm** [comment]
Conflicts are resolved. Thanks.

Issue1: Adding --with-also as a parameter to configure script solves the issue. As there was no gstreamer package detected alsa support should have been enabled (fallback to old behaviour) or an error should have been displayed. Both did not happen. We should make sure old behaviour is not broken. Please make those changes, code can be pulled once it is done. I don't have much idea on autotools so it will be best if you could do the changes to the code.

Issue2: gstreamer-plugins-bad1.0-dev package in Ubuntu 13.04 did not have the .pc file (looks like a bug - planning to file a bug report to Ubuntu). So its not a problem in your code.
But why gstreamer-plugins-bad is necessary? As gstreamer is used for playing audio (not decoding it) gstreamer-plugins-base should suffice right? I will create a .pc file manually and test your code if gstreamer-plugins-bad-1.0 is necessary.

**Comment by mohan43u** [comment]
Issue1: will take a look.

Issue2: libgstrawparse.so contains 'audioparse' plugin for gstreamer which we are using. this lib comes under gstreamer-plugins-bad

**Comment by prasannatsm** [comment]
Okay. I will try compiling code with gstreamer enabled and let you know.

**Comment by mohan43u** [comment]
Hi Prasanna

I fixed fallback issue and another issue while compiling without gstreamer. Its backward compatible now. Merge this request before you commit another change in srini's branch, If conflict occurs I have to rebase again.

**Comment by prasannatsm** [comment]
Thanks Mohan. Merged the code even though I was not able to check the gstreamer stuff. Checked the recent fixes, fallback to older method works well.

**Comment by tshrinivasan** [comment]
Great progress.

Can anyone of you share the development details in the dhvani mailing list?

On Sat, Oct 19, 2013 at 7:37 AM, PrasannaKumar Muralidharan <
notifications@github.com> wrote:

> Thanks Mohan. Merged the code even though I was not able to check the
> gstreamer stuff. Checked the recent fixes, fallback to older method works
> well.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tshrinivasan/dhvani-tts/pull/5#issuecomment-26645380
> .

## 

Regards,
T.Shrinivasan

My Life with GNU/Linux : http://goinggnu.wordpress.com
Free E-Magazine on Free Open Source Software in Tamil : http://kaniyam.com

Get CollabNet Subversion Edge :     http://www.collab.net/svnedge

**Pull request merged**
